export type PteSection = "speaking" | "writing" | "reading" | "listening";
export type PromptSource = "text" | "audio" | "image" | "audio_text" | "none";
export type ResponseKind = "speech" | "text" | "single_choice" | "multiple_choice" | "ordered" | "fill_blanks" | "word_selection";

export interface PteTaskProcedure {
  label: string;
  section: PteSection;
  promptSource: PromptSource;
  responseKind: ResponseKind;
  preparationSeconds: number;
  responseSeconds?: number;
  timeLimitSeconds?: number;
  officialPreparationRange?: readonly [number, number];
  minWords?: number;
  maxWords?: number;
  requiresOptions?: boolean;
  requiresAllSelections?: boolean;
  audioPlaysOnce: boolean;
  scored: boolean;
  scoringDimensions: readonly string[];
}

export const PTE_TASK_PROCEDURES = {
  personal_introduction: {
    label: "Personal Introduction",
    section: "speaking",
    promptSource: "text",
    responseKind: "speech",
    preparationSeconds: 25,
    responseSeconds: 30,
    audioPlaysOnce: false,
    scored: false,
    scoringDimensions: [],
  },
  read_aloud: {
    label: "Read Aloud",
    section: "speaking",
    promptSource: "text",
    responseKind: "speech",
    preparationSeconds: 40,
    officialPreparationRange: [30, 40],
    responseSeconds: 40,
    audioPlaysOnce: false,
    scored: true,
    scoringDimensions: ["content", "pronunciation", "oral_fluency"],
  },
  repeat_sentence: {
    label: "Repeat Sentence",
    section: "speaking",
    promptSource: "audio",
    responseKind: "speech",
    preparationSeconds: 0,
    responseSeconds: 15,
    audioPlaysOnce: true,
    scored: true,
    scoringDimensions: ["content", "pronunciation", "oral_fluency"],
  },
  describe_image: {
    label: "Describe Image",
    section: "speaking",
    promptSource: "image",
    responseKind: "speech",
    preparationSeconds: 25,
    responseSeconds: 40,
    audioPlaysOnce: false,
    scored: true,
    scoringDimensions: ["content", "pronunciation", "oral_fluency"],
  },
  retell_lecture: {
    label: "Retell Lecture",
    section: "speaking",
    promptSource: "audio",
    responseKind: "speech",
    preparationSeconds: 10,
    responseSeconds: 40,
    audioPlaysOnce: true,
    scored: true,
    scoringDimensions: ["content", "pronunciation", "oral_fluency"],
  },
  answer_short_question: {
    label: "Answer Short Question",
    section: "speaking",
    promptSource: "audio",
    responseKind: "speech",
    preparationSeconds: 0,
    responseSeconds: 10,
    audioPlaysOnce: true,
    scored: true,
    scoringDimensions: ["content"],
  },
  summarize_group_discussion: {
    label: "Summarize Group Discussion",
    section: "speaking",
    promptSource: "audio",
    responseKind: "speech",
    preparationSeconds: 10,
    responseSeconds: 120,
    audioPlaysOnce: true,
    scored: true,
    scoringDimensions: ["content", "pronunciation", "oral_fluency"],
  },
  respond_to_situation: {
    label: "Respond to a Situation",
    section: "speaking",
    promptSource: "audio_text",
    responseKind: "speech",
    preparationSeconds: 10,
    responseSeconds: 40,
    audioPlaysOnce: true,
    scored: true,
    scoringDimensions: ["content", "pronunciation", "oral_fluency"],
  },
  summarize_written_text: {
    label: "Summarize Written Text",
    section: "writing",
    promptSource: "text",
    responseKind: "text",
    preparationSeconds: 0,
    timeLimitSeconds: 600,
    minWords: 5,
    maxWords: 75,
    audioPlaysOnce: false,
    scored: true,
    scoringDimensions: ["content", "form", "grammar", "vocabulary"],
  },
  write_essay: {
    label: "Write Essay",
    section: "writing",
    promptSource: "text",
    responseKind: "text",
    preparationSeconds: 0,
    timeLimitSeconds: 1200,
    minWords: 200,
    maxWords: 300,
    audioPlaysOnce: false,
    scored: true,
    scoringDimensions: ["content", "form", "grammar", "vocabulary", "written_discourse"],
  },
  fill_blanks_reading: {
    label: "Fill in the Blanks (Dropdown)",
    section: "reading",
    promptSource: "text",
    responseKind: "fill_blanks",
    preparationSeconds: 0,
    requiresOptions: true,
    requiresAllSelections: true,
    audioPlaysOnce: false,
    scored: true,
    scoringDimensions: ["reading"],
  },
  multiple_choice_multiple: {
    label: "Multiple Choice, Multiple Answers",
    section: "reading",
    promptSource: "text",
    responseKind: "multiple_choice",
    preparationSeconds: 0,
    requiresOptions: true,
    audioPlaysOnce: false,
    scored: true,
    scoringDimensions: ["reading"],
  },
  reorder_paragraphs: {
    label: "Reorder Paragraph",
    section: "reading",
    promptSource: "text",
    responseKind: "ordered",
    preparationSeconds: 0,
    requiresOptions: true,
    requiresAllSelections: true,
    audioPlaysOnce: false,
    scored: true,
    scoringDimensions: ["reading"],
  },
  fill_blanks_rw: {
    label: "Reading and Writing: Fill in the Blanks",
    section: "reading",
    promptSource: "text",
    responseKind: "fill_blanks",
    preparationSeconds: 0,
    requiresOptions: true,
    requiresAllSelections: true,
    audioPlaysOnce: false,
    scored: true,
    scoringDimensions: ["reading", "writing"],
  },
  multiple_choice_single: {
    label: "Multiple Choice, Single Answer",
    section: "reading",
    promptSource: "text",
    responseKind: "single_choice",
    preparationSeconds: 0,
    requiresOptions: true,
    audioPlaysOnce: false,
    scored: true,
    scoringDimensions: ["reading"],
  },
  listening_multiple_choice_multiple: {
    label: "Multiple Choice, Multiple Answers (Listening)",
    section: "listening",
    promptSource: "audio",
    responseKind: "multiple_choice",
    preparationSeconds: 0,
    requiresOptions: true,
    audioPlaysOnce: true,
    scored: true,
    scoringDimensions: ["listening"],
  },
  listening_multiple_choice_single: {
    label: "Multiple Choice, Single Answer (Listening)",
    section: "listening",
    promptSource: "audio",
    responseKind: "single_choice",
    preparationSeconds: 0,
    requiresOptions: true,
    audioPlaysOnce: true,
    scored: true,
    scoringDimensions: ["listening"],
  },
  summarize_spoken_text: {
    label: "Summarize Spoken Text",
    section: "listening",
    promptSource: "audio",
    responseKind: "text",
    preparationSeconds: 0,
    timeLimitSeconds: 600,
    minWords: 50,
    maxWords: 70,
    audioPlaysOnce: true,
    scored: true,
    scoringDimensions: ["listening", "writing"],
  },
  fill_blanks_listening: {
    label: "Fill in the Blanks (Type In)",
    section: "listening",
    promptSource: "audio",
    responseKind: "text",
    preparationSeconds: 0,
    audioPlaysOnce: true,
    scored: true,
    scoringDimensions: ["listening"],
  },
  highlight_correct_summary: {
    label: "Highlight Correct Summary",
    section: "listening",
    promptSource: "audio",
    responseKind: "single_choice",
    preparationSeconds: 0,
    requiresOptions: true,
    audioPlaysOnce: true,
    scored: true,
    scoringDimensions: ["listening"],
  },
  select_missing_word: {
    label: "Select Missing Word",
    section: "listening",
    promptSource: "audio",
    responseKind: "single_choice",
    preparationSeconds: 0,
    requiresOptions: true,
    audioPlaysOnce: true,
    scored: true,
    scoringDimensions: ["listening"],
  },
  highlight_incorrect_words: {
    label: "Highlight Incorrect Words",
    section: "listening",
    promptSource: "audio_text",
    responseKind: "word_selection",
    preparationSeconds: 0,
    requiresOptions: false,
    audioPlaysOnce: true,
    scored: true,
    scoringDimensions: ["listening"],
  },
  write_from_dictation: {
    label: "Write from Dictation",
    section: "listening",
    promptSource: "audio",
    responseKind: "text",
    preparationSeconds: 0,
    audioPlaysOnce: true,
    scored: true,
    scoringDimensions: ["listening", "writing"],
  },
} as const satisfies Record<string, PteTaskProcedure>;

export type PteTaskType = keyof typeof PTE_TASK_PROCEDURES;

export function getPteTaskProcedure(taskType: string, section?: PteSection): PteTaskProcedure | undefined {
  const sectionSpecificType = section ? `${section}_${taskType}` : undefined;
  return (sectionSpecificType && PTE_TASK_PROCEDURES[sectionSpecificType as PteTaskType])
    || PTE_TASK_PROCEDURES[taskType as PteTaskType];
}
